### ISSUE TITLE
dissoc null values in json objects

### ISSUE THREAD

**Issue by yvern** [janet-lang/json#2]
why not remove null keys in json maps?

**Comment by bakpakin** [comment]
Issue is not clear, please provide an example and a longer description.

**Comment by yvern** [comment]
sorry, here’s what I meant:

according to documentation, JSON accepts `null` as value for an object, and janet tables do not. my suggestion would be removing said key/value from resulting table, instead of using the `:null` keyword.

**Comment by bakpakin** [comment]
The :null keyword is used to differentiate between an empty object and an object with null values. If we used nil for null, the results would be identical although they are semantically different JSON.

With null = nil:
```
(json/decode `{"abc": null}`) #-> {}
(json/decode `{}`) #-> {}
```
This is probably what  you want most of the time, but sometimes you would want to know that a key existed, even if the value was nil.
