### ISSUE TITLE
Building with jpm fails on Windows 10 / MSYS2

### ISSUE THREAD

**Issue by IcedQuinn** [janet-lang/json#5]
1. Install Janet on msys2 using the makefile. This works except installation fails trying to symlink between libjanet.so and libjanet.so.1.15.5.
2. Remove build artifacts and install Janet with meson build. This works and ninja install succeeds.
3. Faffing around with symbol visibility (ex. changing janet's meson script to include -Wl,--export-all-symbols, removing -fsymbol-visibilities, 

In both cases attempting to install janet-json with jpm build fails citing undefined references to basic janet symbols.

```
$ jpm build
compiling json.c to build/json.o...
linking build/json.so...
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: build/json.o:json.c:(.text+0x19): undefined reference to `janet_buffer_push_bytes'
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: build/json.o:json.c:(.text+0x47): undefined reference to `janet_buffer_push_bytes'
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: build/json.o:json.c:(.text+0xa8): undefined reference to `janet_buffer_push_cstring'
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: build/json.o:json.c:(.text+0xf1): undefined reference to `janet_bytes_view'
[snip]
```

Haven't quite pinned down if this is a visibility issue or if jpm is just not telling the compiler where to find and use the library. I did not see a way to get jpm to spit out the raw command before running it to tell the difference either.

**Comment by bakpakin** [comment]
Err, this is a bit old. jpm was never designed to work with msys anyway, I expect there would be some issues without custom configuration.

**Comment by IcedQuinn** [comment]
I never figured out why it did it over there. Ended up just writing the JSON dumper in Janet itself.
